List<String> languages = [
  "Hindi",
  "English",
  "Bengali",
  "Marathi",
  "Telugu",
  "Tamil",
  "Urdu",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Punjabi"
];
List<String> certificatesExt = ['jpg', 'jpeg', 'pdf'];
List<String> states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Andaman and Nicobar Islands",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
];

List astrologerSpecializations = [
  "Vedic Astrology",
  "KP Astrology",
  "Palmistry",
  "Tarot Reading",
  "Numerology",
  "Face Reading",
  "Vastu",
  "Others"
];
