// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHn2yIG6Mkva8IPnYnbESubhRhqX2Ug_Y',
    appId: '1:683196372486:web:e5f4e0f1a7767e08b15587',
    messagingSenderId: '683196372486',
    projectId: 'astro-99c72',
    authDomain: 'astro-99c72.firebaseapp.com',
    storageBucket: 'astro-99c72.firebasestorage.app',
    measurementId: 'G-HVD4SG93W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsT7xnQ0Kt77BZZF3UQ-uuP1TyKUOy_ak',
    appId: '1:683196372486:android:ff2329751a56d47ab15587',
    messagingSenderId: '683196372486',
    projectId: 'astro-99c72',
    storageBucket: 'astro-99c72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBapezBkv9fUN-4NFw44A-dflIA2Mpw3JM',
    appId: '1:683196372486:ios:683d6fcd1cef9f2db15587',
    messagingSenderId: '683196372486',
    projectId: 'astro-99c72',
    storageBucket: 'astro-99c72.firebasestorage.app',
    androidClientId: '683196372486-1id05d3drs86huk81nnnek4iupjjm7ga.apps.googleusercontent.com',
    iosClientId: '683196372486-5mr29dl6vq3jbll2t7n4qtaffhfgaakn.apps.googleusercontent.com',
    iosBundleId: 'com.foreastro.astrologer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBapezBkv9fUN-4NFw44A-dflIA2Mpw3JM',
    appId: '1:683196372486:ios:7aa473b1af176d2ab15587',
    messagingSenderId: '683196372486',
    projectId: 'astro-99c72',
    storageBucket: 'astro-99c72.firebasestorage.app',
    androidClientId: '683196372486-1id05d3drs86huk81nnnek4iupjjm7ga.apps.googleusercontent.com',
    iosClientId: '683196372486-ppl01akf4pq9mgiobu8q28m3isfp908r.apps.googleusercontent.com',
    iosBundleId: 'com.example.foreAstro2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHn2yIG6Mkva8IPnYnbESubhRhqX2Ug_Y',
    appId: '1:683196372486:web:f15767991ce57f86b15587',
    messagingSenderId: '683196372486',
    projectId: 'astro-99c72',
    authDomain: 'astro-99c72.firebaseapp.com',
    storageBucket: 'astro-99c72.firebasestorage.app',
    measurementId: 'G-LKN9PQKCV5',
  );

}

FirebaseMessaging firebaseMessaging = FirebaseMessaging.instance;